CREATE TABLE IF NOT EXISTS outbox_events (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     TIMESTAMPTZ DEFAULT NOW(),
    updated_at     TIMESTAMPTZ DEFAULT NOW(),
    deleted_at     TIMESTAMPTZ NULL,
    aggregate_type TEXT NOT NULL,
    aggregate_id   BIGINT NOT NULL,
    event_type     TEXT NOT NULL,
    payload        JSONB NOT NULL,
    status         TEXT NOT NULL DEFAULT 'pending',
    retry_count    INT NOT NULL DEFAULT 0,
    next_retry_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index cho worker poll: hốt batch pending tới hạn theo thứ tự.
CREATE INDEX IF NOT EXISTS idx_outbox_events_status_retry
    ON outbox_events (status, next_retry_at, id);
