basePath: /
definitions:
  dtos.ResponseResource:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
info:
  contact: {}
  description: Knowledge ingestion service
  title: Knowledge Ingestion API
  version: "1.0"
paths:
  /api/v1/ping:
    get:
      description: Returns pong with server timestamp
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.ResponseResource'
      summary: Ping the server
      tags:
      - health
  /api/v1/pong:
    get:
      description: Returns ping with server timestamp
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.ResponseResource'
      summary: Pong the server
      tags:
      - health
swagger: "2.0"
